import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, Sparkles, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../api";
import { useSession } from "../App";

const particles = Array.from({length:18},(_,i)=>({left:`${(i*37)%97}%`,top:`${(i*53)%91}%`,delay:(i%7)*.4,size:2+(i%4)}));

export default function Auth({ mode }) {
  const register=mode==="register"; const navigate=useNavigate(); const {refresh}=useSession();
  const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const submit=async(event)=>{event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);try{await api(`/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify(Object.fromEntries(form))});await refresh();navigate("/app/dashboard")}catch(err){setError(err.message)}finally{setLoading(false)}};
  return <main className="relative grid min-h-screen overflow-hidden bg-void lg:grid-cols-[1.05fr_.95fr]">
    <div className="pointer-events-none absolute inset-0 grid-noise opacity-60"/><div className="aurora pointer-events-none absolute -left-40 -top-40 h-[34rem] w-[34rem] rounded-full bg-primary/20 blur-[100px]"/><div className="aurora pointer-events-none absolute -bottom-48 right-0 h-[36rem] w-[36rem] rounded-full bg-cyan/10 blur-[110px]"/>
    {particles.map((p,i)=><span key={i} className="particle absolute rounded-full bg-cyan/50 shadow-[0_0_8px_#22d3ee]" style={{...p,width:p.size,height:p.size,animationDelay:`${p.delay}s`}}/>)}
    <section className="relative z-10 hidden flex-col justify-between p-12 lg:flex xl:p-20"><Link to="/app/login" className="flex items-center gap-3"><img src="/static/images/finsight-ai-logo.png" alt="FinSight AI" className="h-14 w-14 rounded-2xl object-cover shadow-glow"/><span className="text-xl font-bold">FinSight <span className="text-cyan">AI</span></span></Link><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan/20 bg-cyan/5 px-3 py-1.5 text-xs font-semibold text-cyan"><Sparkles size={14}/> FINANCE, WITH FORESIGHT</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.08] tracking-[-.04em] xl:text-7xl">Your money.<br/><span className="text-gradient">Finally intelligent.</span></h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-muted">One calm, beautifully clear workspace for spending, saving, and AI-powered financial decisions.</p></motion.div><p className="text-xs text-slate-600">© 2026 FinSight AI · Private by design</p></section>
    <section className="relative z-10 grid place-items-center px-4 py-10 sm:px-8"><motion.div initial={{opacity:0,y:24,scale:.98}} animate={{opacity:1,y:0,scale:1}} transition={{duration:.55,ease:[.22,1,.36,1]}} className="glass neon-border w-full max-w-md rounded-[32px] p-6 sm:p-9"><div className="mb-8 flex items-center gap-3 lg:hidden"><img src="/static/images/finsight-ai-logo.png" alt="" className="h-12 w-12 rounded-xl"/><span className="font-bold">FinSight AI</span></div><div className="mb-7"><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">{register?"Create your account":"Welcome back"}</h2><p className="mt-2 text-sm text-muted">{register?"Start making smarter money moves today.":"Your financial command center is ready."}</p></div>
      <button type="button" onClick={()=>setError("Google sign-in needs an OAuth client ID before it can be enabled.")} className="flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-white/[.09] bg-white/[.035] text-sm font-semibold transition hover:-translate-y-0.5 hover:border-white/20 hover:bg-white/[.06]"><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-xs font-bold text-blue-500">G</span>Continue with Google</button><div className="my-6 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-600"><span className="h-px flex-1 bg-white/[.07]"/>or use email<span className="h-px flex-1 bg-white/[.07]"/></div>
      <form onSubmit={submit} className="space-y-4">{register&&<Field icon={UserRound} name="name" label="Full name" placeholder="Aryan Mevada" autoComplete="name"/>}<Field icon={Mail} name="email" label="Email" type="email" placeholder="you@example.com" autoComplete="email"/><div><label htmlFor="password" className="mb-2 block text-xs font-semibold text-slate-300">Password</label><div className="relative"><LockKeyhole className="absolute left-3.5 top-3.5 text-slate-500" size={17}/><input id="password" required minLength={register?8:1} name="password" type={show?"text":"password"} autoComplete={register?"new-password":"current-password"} className="h-12 w-full rounded-xl border border-white/[.08] bg-black/20 pl-11 pr-11 text-sm outline-none transition placeholder:text-slate-700 focus:border-primary/60 focus:ring-4 focus:ring-primary/10" placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3 rounded-lg p-1 text-slate-500 hover:text-white" aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>{register&&<Field icon={LockKeyhole} name="confirmPassword" label="Confirm password" type={show?"text":"password"} placeholder="••••••••" autoComplete="new-password"/>}{!register&&<div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2 text-muted"><input type="checkbox" name="remember" value="true" className="accent-primary"/>Remember me</label><button type="button" className="text-cyan hover:text-white">Forgot password?</button></div>}{error&&<motion.p initial={{opacity:0,y:-4}} animate={{opacity:1,y:0}} role="alert" className="rounded-xl border border-danger/20 bg-danger/10 p-3 text-xs text-red-300">{error}</motion.p>}<motion.button type="submit" whileHover={{y:-2}} whileTap={{scale:.98}} disabled={loading} className="group flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-primary to-blue-500 text-sm font-bold shadow-[0_10px_30px_rgba(59,130,246,.25)] transition disabled:opacity-60">{loading?"Securing your session...":register?"Create account":"Enter FinSight"}<ArrowRight size={17} className="transition-transform group-hover:translate-x-1"/></motion.button></form><p className="mt-6 text-center text-xs text-muted">{register?"Already have an account?":"New to FinSight AI?"} <Link className="font-semibold text-cyan hover:text-white" to={register?"/app/login":"/app/register"}>{register?"Log in":"Create an account"}</Link></p></motion.div></section>
  </main>;
}

function Field({icon:Icon,label,name,...props}) { return <div><label htmlFor={name} className="mb-2 block text-xs font-semibold text-slate-300">{label}</label><div className="relative"><Icon className="absolute left-3.5 top-3.5 text-slate-500" size={17}/><input id={name} name={name} required {...props} className="h-12 w-full rounded-xl border border-white/[.08] bg-black/20 pl-11 pr-3 text-sm outline-none transition placeholder:text-slate-700 focus:border-primary/60 focus:ring-4 focus:ring-primary/10"/></div></div> }
