import { useEffect, useMemo, useRef, useState } from "react";
import { motion, useInView } from "framer-motion";
import {
  ArrowDownRight, ArrowUpRight, Bot, BriefcaseBusiness, Car, CircleDollarSign,
  Clapperboard, CreditCard, Lightbulb, PiggyBank, Receipt, ShoppingBag,
  Sparkles, Target, TrendingDown, TrendingUp, Utensils, Wallet,
} from "lucide-react";
import {
  Area, AreaChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { api, money } from "../api";
import { useSession } from "../App";

const palette=["#3B82F6","#22D3EE","#10B981","#F59E0B","#8B5CF6","#EC4899"];
const categoryIcons={Food:Utensils,Shopping:ShoppingBag,Bills:Receipt,Transport:Car,Entertainment:Clapperboard};
const reveal={hidden:{opacity:0,y:22},show:{opacity:1,y:0,transition:{duration:.55,ease:[.22,1,.36,1]}}};

function CountUp({value,currency=true}) { const [display,setDisplay]=useState(0); const {session}=useSession(); useEffect(()=>{let start;const duration=900;let raf;const tick=t=>{start??=t;const progress=Math.min((t-start)/duration,1);setDisplay(value*(1-Math.pow(1-progress,3)));if(progress<1)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[value]);return currency?money(display,session.user.currency):Math.round(display) }
function Glass({children,className="",...props}) { return <motion.section variants={reveal} whileHover={{y:-4}} transition={{duration:.22}} className={`glass neon-border rounded-[24px] ${className}`} {...props}>{children}</motion.section> }
function Skeleton(){return <div className="grid gap-5"><div className="shimmer h-64 rounded-[28px]"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="shimmer h-40 rounded-3xl"/>)}</div><div className="grid gap-5 xl:grid-cols-2"><div className="shimmer h-80 rounded-3xl"/><div className="shimmer h-80 rounded-3xl"/></div></div>}

export default function Dashboard(){
  const [data,setData]=useState(null); const [error,setError]=useState(""); const {session}=useSession();
  useEffect(()=>{api("/dashboard").then(setData).catch(e=>setError(e.message))},[]);
  if(error)return <div className="glass rounded-3xl p-8 text-red-300">{error}</div>; if(!data)return <Skeleton/>;
  const monthly=data.charts.monthlySpending.labels.map((label,i)=>({label,expense:data.charts.monthlySpending.values[i]}));
  const categories=data.charts.expenseCategories.labels.map((name,i)=>({name,value:data.charts.expenseCategories.values[i]}));
  const statData=monthly.length?monthly:[{label:"Now",expense:0}];
  return <motion.div initial="hidden" animate="show" className="mx-auto max-w-[1600px] space-y-5">
    <motion.div variants={reveal} className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><span className="text-xs font-semibold uppercase tracking-[.2em] text-cyan">Financial command center</span><h2 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Your money, in focus.</h2></div><p className="max-w-md text-sm text-muted">Live intelligence built from your income, spending, and budget patterns.</p></motion.div>
    <Hero data={data}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Total balance" value={data.metrics.balance} icon={Wallet} color="#3B82F6" trend="12.4%" chart={statData}/><Stat title="Total income" value={data.metrics.income} icon={TrendingUp} color="#10B981" trend="8.2%" chart={statData.map(x=>({...x,expense:x.expense*.8+100}))}/><Stat title="Total expense" value={data.metrics.expense} icon={TrendingDown} color="#EF4444" trend="3.1%" negative chart={statData}/><Stat title="Monthly savings" value={data.metrics.savings} icon={PiggyBank} color="#22D3EE" trend="6.8%" chart={statData.map(x=>({...x,expense:x.expense*.35}))}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.45fr_.85fr]"><SpendingChart data={monthly}/><CategoryChart data={categories}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Transactions rows={data.transactions}/><Budget budget={data.budget}/></div>
    <div className="grid gap-5 lg:grid-cols-3"><Goals data={data}/><Recommendation text={data.health.insight}/><Forecast data={data}/></div>
  </motion.div>;
}

function Hero({data}){return <Glass className="relative overflow-hidden p-6 sm:p-8" whileHover={{y:0}}><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_15%,rgba(34,211,238,.14),transparent_30%),linear-gradient(110deg,rgba(59,130,246,.13),transparent_48%)]"/><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full border border-cyan/10"/><div className="relative grid gap-8 lg:grid-cols-[1.3fr_.7fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full border border-cyan/20 bg-cyan/5 px-3 py-1.5 text-xs font-semibold text-cyan"><Sparkles size={14}/> AI FINANCIAL PULSE</span><h3 className="mt-5 max-w-3xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">You’re building stronger financial momentum.</h3><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted sm:text-base">{data.health.insight}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><p className="text-xs text-muted">Savings prediction · 12 months</p><p className="mt-1 text-xl font-bold text-cyan"><CountUp value={data.health.prediction}/></p></div><div className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><p className="text-xs text-muted">Budget utilization</p><p className="mt-1 text-xl font-bold">{data.budget.percentage}% <span className="text-xs font-normal text-muted">this month</span></p></div></div></div><Gauge score={data.health.score}/></div></Glass>}

function Gauge({score}){const color=score>=75?"#10B981":score>=50?"#F59E0B":"#EF4444";const circumference=2*Math.PI*70;return <div className="mx-auto text-center"><div className="relative h-48 w-48"><svg viewBox="0 0 180 180" className="-rotate-90"><circle cx="90" cy="90" r="70" fill="none" stroke="rgba(148,163,184,.1)" strokeWidth="12"/><motion.circle cx="90" cy="90" r="70" fill="none" stroke={color} strokeWidth="12" strokeLinecap="round" strokeDasharray={circumference} initial={{strokeDashoffset:circumference}} animate={{strokeDashoffset:circumference*(1-score/100)}} transition={{duration:1.4,ease:"easeOut"}} style={{filter:`drop-shadow(0 0 10px ${color}70)`}}/></svg><div className="absolute inset-0 grid place-items-center"><div><p className="text-4xl font-extrabold"><CountUp value={score} currency={false}/></p><p className="text-xs text-muted">out of 100</p></div></div></div><p className="mt-1 text-xs font-semibold uppercase tracking-[.18em]" style={{color}}>Financial health</p></div>}

function Stat({title,value,icon:Icon,color,trend,negative,chart}){return <Glass className="group overflow-hidden p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl" style={{background:`${color}18`,color}}><Icon size={20}/></span><span className={`flex items-center gap-1 text-xs font-semibold ${negative?"text-red-400":"text-success"}`}>{negative?<ArrowDownRight size={14}/>:<ArrowUpRight size={14}/>} {trend}</span></div><p className="mt-5 text-xs font-medium text-muted">{title}</p><p className="mt-1 text-2xl font-bold tracking-tight"><CountUp value={value}/></p><div className="-mb-5 -mr-5 mt-2 h-12 w-28 opacity-70"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id={`g-${title}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity={.35}/><stop offset="1" stopColor={color} stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="expense" stroke={color} strokeWidth={2} fill={`url(#g-${title})`} isAnimationActive/></AreaChart></ResponsiveContainer></div></Glass>}

function SpendingChart({data}){return <Glass className="p-5 sm:p-6"><Title title="Monthly expense trend" subtitle="Six-month spending movement"/><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-18,right:8}}><defs><linearGradient id="expenseArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3B82F6" stopOpacity={.38}/><stop offset="1" stopColor="#3B82F6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.07)" vertical={false}/><XAxis dataKey="label" stroke="#64748b" tickLine={false} axisLine={false} tick={{fontSize:11}}/><YAxis stroke="#64748b" tickLine={false} axisLine={false} tick={{fontSize:11}}/><Tooltip content={<ChartTooltip/>}/><Area type="monotone" dataKey="expense" stroke="#3B82F6" strokeWidth={3} fill="url(#expenseArea)" animationDuration={1200}/></AreaChart></ResponsiveContainer></div></Glass>}
function CategoryChart({data}){const total=data.reduce((s,x)=>s+x.value,0);return <Glass className="p-5 sm:p-6"><Title title="Category breakdown" subtitle="Where your money is going"/><div className="relative mt-3 h-52"><ResponsiveContainer><PieChart><Pie data={data.length?data:[{name:"No data",value:1}]} dataKey="value" innerRadius={64} outerRadius={88} paddingAngle={4} stroke="none" animationDuration={1100}>{(data.length?data:[1]).map((_,i)=><Cell key={i} fill={data.length?palette[i%palette.length]:"#1e293b"}/>)}</Pie><Tooltip content={<ChartTooltip/>}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="text-xl font-bold">{money(total)}</p><p className="text-[10px] text-muted">TOTAL SPENT</p></div></div></div><div className="grid grid-cols-2 gap-2">{data.slice(0,6).map((x,i)=><div key={x.name} className="flex items-center gap-2 text-xs text-muted"><span className="h-2 w-2 rounded-full" style={{background:palette[i%palette.length]}}/>{x.name}</div>)}</div></Glass>}
function ChartTooltip({active,payload,label}){if(!active||!payload?.length)return null;return <div className="rounded-xl border border-white/10 bg-slate-950/95 px-3 py-2 text-xs shadow-xl"><p className="text-muted">{label||payload[0].name}</p><b>{money(payload[0].value)}</b></div>}
function Title({title,subtitle}){return <div className="flex items-center justify-between"><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-muted">{subtitle}</p></div><button className="rounded-xl border border-white/[.07] p-2 text-muted transition hover:border-primary/30 hover:text-white" aria-label={`Options for ${title}`}><CircleDollarSign size={17}/></button></div>}

function Transactions({rows}){return <Glass className="p-5 sm:p-6"><Title title="Recent transactions" subtitle="Your latest account activity"/><div className="mt-5 space-y-2">{rows.length?rows.slice(0,5).map((row,i)=>{const Icon=row.type==="income"?BriefcaseBusiness:(categoryIcons[row.category]||CreditCard);return <motion.div key={`${row.type}-${row.id}`} initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:i*.06}} whileHover={{x:4,scale:1.005}} className="flex items-center gap-3 rounded-2xl border border-transparent p-3 transition hover:border-primary/20 hover:bg-primary/[.04]"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${row.type==="income"?"bg-success/10 text-success":"bg-primary/10 text-blue-300"}`}><Icon size={19}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.description}</p><div className="mt-1 flex items-center gap-2 text-[11px] text-muted"><span className="rounded-md bg-white/[.05] px-1.5 py-0.5">{row.category}</span><span>{new Date(`${row.date}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span></div></div><div className="text-right"><p className={`text-sm font-bold ${row.amount>0?"text-success":"text-white"}`}>{row.amount>0?"+":""}{money(row.amount)}</p><span className="text-[10px] text-success">● {row.status}</span></div></motion.div>}):<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-muted">No transactions yet. Add income or an expense to begin.</div>}</div></Glass>}

function Budget({budget}){const defaults=["Food","Shopping","Bills","Transport","Entertainment"];const map=Object.fromEntries(budget.categories.map(x=>[x.name,x.spent]));const allocations={Food:.25,Shopping:.15,Bills:.3,Transport:.15,Entertainment:.15};return <Glass className="p-5 sm:p-6"><Title title="Budget control" subtitle={`${budget.percentage}% of monthly plan used`}/><div className="mt-6 space-y-5">{defaults.map((name,i)=>{const Icon=categoryIcons[name];const limit=budget.limit*allocations[name];const pct=limit?Math.min((map[name]||0)/limit*100,100):0;return <div key={name}><div className="mb-2 flex items-center justify-between text-xs"><span className="flex items-center gap-2 font-semibold"><Icon size={15} style={{color:palette[i]}}/>{name}</span><span className="text-muted">{money(map[name]||0)} <span className="text-slate-600">/ {money(limit)}</span></span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.05]"><motion.div initial={{width:0}} whileInView={{width:`${pct}%`}} viewport={{once:true}} transition={{duration:1,delay:i*.08}} className="h-full rounded-full" style={{background:`linear-gradient(90deg,${palette[i]},${palette[(i+1)%palette.length]})`,boxShadow:`0 0 12px ${palette[i]}70`}}/></div></div>})}</div></Glass>}

function Goals({data}){const goals=[{name:"Laptop",target:120000,value:Math.max(data.metrics.savings*2,18000),color:"#3B82F6"},{name:"Vacation",target:80000,value:Math.max(data.metrics.savings,22000),color:"#22D3EE"},{name:"Emergency",target:200000,value:Math.max(data.metrics.balance*.1,45000),color:"#10B981"}];return <Glass className="p-5"><Title title="Savings goals" subtitle="Momentum toward what matters"/><div className="mt-5 grid grid-cols-3 gap-2">{goals.map(g=>{const pct=Math.min(g.value/g.target*100,100);return <div key={g.name} className="text-center"><div className="relative mx-auto h-16 w-16"><svg className="-rotate-90" viewBox="0 0 64 64"><circle cx="32" cy="32" r="26" fill="none" stroke="rgba(255,255,255,.06)" strokeWidth="5"/><motion.circle cx="32" cy="32" r="26" fill="none" stroke={g.color} strokeWidth="5" strokeLinecap="round" pathLength="100" initial={{strokeDasharray:"0 100"}} whileInView={{strokeDasharray:`${pct} 100`}} transition={{duration:1}}/></svg><span className="absolute inset-0 grid place-items-center text-[10px] font-bold">{Math.round(pct)}%</span></div><p className="mt-2 text-[11px] font-semibold">{g.name}</p></div>})}</div></Glass>}
function Recommendation({text}){const [shown,setShown]=useState("");useEffect(()=>{let i=0;const id=setInterval(()=>{i++;setShown(text.slice(0,i));if(i>=text.length)clearInterval(id)},24);return()=>clearInterval(id)},[text]);return <Glass className="p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan/10 text-cyan"><Bot size={20}/></span><div><h3 className="text-sm font-semibold">AI recommendation</h3><p className="text-[10px] text-success">● LIVE INSIGHT</p></div></div><p className="mt-5 min-h-14 text-sm leading-relaxed text-slate-300">{shown}<span className="ml-1 inline-block h-4 w-0.5 animate-pulse bg-cyan"/></p><button className="mt-4 flex items-center gap-2 text-xs font-semibold text-cyan hover:text-white"><Sparkles size={14}/> Explore with AI</button></Glass>}
function Forecast({data}){return <Glass className="overflow-hidden p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-success/10 text-success"><Target size={20}/></span><span className="rounded-full bg-success/10 px-2 py-1 text-[10px] font-semibold text-success">ON TRACK</span></div><p className="mt-5 text-xs text-muted">Projected annual savings</p><p className="mt-1 text-2xl font-bold"><CountUp value={data.health.prediction}/></p><p className="mt-3 text-xs leading-relaxed text-muted">Based on your current monthly cash-flow trajectory.</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/5"><motion.div initial={{width:0}} whileInView={{width:"72%"}} transition={{duration:1.2}} className="h-full rounded-full bg-gradient-to-r from-success to-cyan shadow-[0_0_12px_rgba(16,185,129,.5)]"/></div></Glass>}
