import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowDownLeft, ArrowUpRight, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { api, money } from "../api";
import { useSession } from "../App";

export default function Transactions(){
  const [data,setData]=useState(null),[tab,setTab]=useState("expenses"),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[error,setError]=useState(""); const {session}=useSession();
  const load=()=>api("/transactions").then(setData); useEffect(()=>{load()},[]);
  const rows=data?.[tab]||[]; const kind=tab==="expenses"?"expense":"income";
  const submit=async(e)=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget));try{await api(`/${tab}${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(payload)});setModal(false);setEditing(null);setError("");load()}catch(err){setError(err.message)}};
  const remove=async id=>{if(!confirm(`Delete this ${kind}?`))return;await api(`/${tab}/${id}`,{method:"DELETE"});load()};
  return <motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-xs font-semibold uppercase tracking-[.2em] text-cyan">Money movement</span><h2 className="mt-2 text-3xl font-bold">Transactions</h2><p className="mt-2 text-sm text-muted">Every inflow and outflow, clearly organized.</p></div><motion.button whileHover={{y:-2}} whileTap={{scale:.97}} onClick={()=>{setEditing(null);setModal(true)}} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold shadow-glow"><Plus size={18}/> Add {kind}</motion.button></header>
    <div className="glass rounded-[26px] p-4 sm:p-6"><div className="flex flex-col justify-between gap-4 border-b border-white/[.07] pb-5 sm:flex-row"><div className="flex rounded-xl bg-black/20 p-1">{["expenses","incomes"].map(key=><button key={key} onClick={()=>setTab(key)} className={`relative rounded-lg px-4 py-2 text-xs font-semibold capitalize ${tab===key?"text-white":"text-muted"}`}>{tab===key&&<motion.span layoutId="tx-tab" className="absolute inset-0 -z-10 rounded-lg bg-primary/20"/>}{key}</button>)}</div><label className="flex items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.03] px-3"><Search size={16} className="text-muted"/><input placeholder="Search transactions" className="h-10 bg-transparent text-sm outline-none placeholder:text-slate-600"/></label></div>
      <div className="mt-4 space-y-2">{!data?[1,2,3,4].map(i=><div key={i} className="shimmer h-16 rounded-2xl"/>):rows.length?rows.map((row,i)=><motion.article key={row.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.035}} whileHover={{scale:1.005,x:3}} className="group flex items-center gap-3 rounded-2xl border border-transparent p-3 transition hover:border-primary/20 hover:bg-primary/[.035]"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${tab==="expenses"?"bg-danger/10 text-red-300":"bg-success/10 text-success"}`}>{tab==="expenses"?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.description||row.category||row.source}</p><p className="mt-1 text-xs text-muted">{row.category||row.source} · {new Date(`${row.date}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</p></div><p className={`hidden text-sm font-bold sm:block ${tab==="incomes"?"text-success":""}`}>{tab==="incomes"?"+":"-"}{money(row.amount,session.user.currency)}</p><div className="flex opacity-100 transition sm:opacity-0 sm:group-hover:opacity-100"><button onClick={()=>{setEditing(row);setModal(true)}} aria-label="Edit" className="rounded-lg p-2 text-muted hover:bg-white/5 hover:text-white"><Pencil size={16}/></button><button onClick={()=>remove(row.id)} aria-label="Delete" className="rounded-lg p-2 text-muted hover:bg-danger/10 hover:text-red-300"><Trash2 size={16}/></button></div></motion.article>):<div className="py-20 text-center text-sm text-muted">No {tab} recorded yet.</div>}</div>
    </div>
    <AnimatePresence>{modal&&<div className="fixed inset-0 z-[70] grid place-items-center p-4"><motion.button aria-label="Close" className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={()=>setModal(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.form onSubmit={submit} initial={{opacity:0,y:20,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20,scale:.96}} className="glass relative z-10 w-full max-w-lg rounded-[28px] p-6"><div className="flex items-center justify-between"><div><h3 className="text-xl font-bold">{editing?"Edit":"Add"} {kind}</h3><p className="mt-1 text-xs text-muted">Keep your financial picture accurate.</p></div><button type="button" onClick={()=>setModal(false)} className="rounded-xl p-2 text-muted hover:bg-white/5"><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field name="amount" label="Amount" type="number" min="0.01" step="0.01" defaultValue={editing?.amount}/><Field name="date" label="Date" type="date" defaultValue={editing?.date||new Date().toISOString().slice(0,10)}/><label className="sm:col-span-2"><span className="mb-2 block text-xs font-semibold text-slate-300">{tab==="expenses"?"Category":"Source"}</span><select required name={tab==="expenses"?"category":"source"} defaultValue={editing?.category||editing?.source||""} className="h-12 w-full rounded-xl border border-white/[.08] bg-slate-950 px-3 text-sm outline-none focus:border-primary"><option value="" disabled>Select one</option>{(tab==="expenses"?data.expenseCategories:data.incomeSources).map(x=><option key={x}>{x}</option>)}</select></label><label className="sm:col-span-2"><span className="mb-2 block text-xs font-semibold text-slate-300">Description</span><textarea name="description" defaultValue={editing?.description||""} rows="3" className="w-full rounded-xl border border-white/[.08] bg-black/20 p-3 text-sm outline-none focus:border-primary" placeholder="Optional note"/></label></div>{error&&<p className="mt-4 rounded-xl bg-danger/10 p-3 text-xs text-red-300">{error}</p>}<button className="mt-6 h-12 w-full rounded-xl bg-primary text-sm font-bold shadow-glow">Save {kind}</button></motion.form></div>}</AnimatePresence>
  </motion.div>;
}
function Field({label,...props}){return <label><span className="mb-2 block text-xs font-semibold text-slate-300">{label}</span><input required {...props} className="h-12 w-full rounded-xl border border-white/[.08] bg-black/20 px-3 text-sm outline-none focus:border-primary"/></label>}
